FROM almalinux:9

RUN dnf install nginx -y

CMD ["nginx", "-g", "daemon off;"]
#CMD ["sleep", "100"]

ENV name="Vijaya" \
    profession="Devops Engineer" \
    location="UK"

LABEL name="Vijaya" \
      profession="Devops Engineer" \
      location="UK"