apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:            # these are replicaset labels
    app: nginx
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:     # these are used to select the pod to create replicas
      tier: frontend
      app: nginx
  template:
    metadata:
      labels:        # these labels belongs to pod
        tier: frontend
        app: nginx
  spec:
    containers:
      - name: nginx
        image: nginx
        #image: nginx:stable-perl
